### ISSUE TITLE
Support for MSTest?

### ISSUE THREAD

**Issue by ffMathy** [criteo/NinjaTurtlesMutation#1]
This concept is awesome. Would it be possible to support MSTest, or is there some kind of reason it is not supported?

**Comment by TonyRoussel** [comment]
Hi,
Only NUnit is supported on NTM, so it can really focus on speed by using its dll to run tests.

NinjaTurles support [a lot more test framework](http://ninjaturtles.codeplex.com/SourceControl/latest#NinjaTurtles/TestRunners/), including MSTest, by calling a test process (nunit-console.exe for nunit, MSTest.exe for mstest etc...) by mutant, which is time consuming.

Also, focusing on a single test framework avoid writing specific test discovery methods for each of them
